############################ Default configuration #########################
baseURL = "https://kjw217.github.io/"
languageCode = "ko-kr"
# site title 
title = "References"
# theme
theme = "northendlab-hugo"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


########################### Navigation ###################################

# main menu
[[menu.main]]
URL = "posts"
name = "Posts"
identifier = "Posts"
weight = 1

[[menu.main]]
URL = "posts/languages/"
name = "Languages"
identifier = "Languages"
parent = "Posts"

[[menu.main]]
URL = "posts/languages/python/"
name = "Python"
parent = "Languages"

[[menu.main]]
URL = "posts/languages/go/"
name = "GO"
parent = "Languages"

######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo_re.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true


####################### banner #######################################
[params.banner]
bgImage = "images/banner/joke-white.png"
title = ""
image = ""


######################## call to action ###############################
[params.cta]
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"


############################## Social Site ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/kjw217"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "#"

################################# Taxonomies #############################
[taxonomies]
tag = "tags"
category = "categories"